name: Build Android Gateway APK

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: NEW - List files to see if yarn.lock is present
      - name: List files in the repository
        run: ls -la

      # Step 3: Set up JDK version 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Set up Node.js version 18
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      # Step 5: Install Yarn Dependencies
      - name: Install Yarn Dependencies
        run: yarn install

      # Step 6: Build the release APK
      - name: Build Android Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # Step 7: Upload the generated APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsm-sip-gateway-apk
          path: android/app/build/outputs/apk/release/app-release.apk
