name: Build Android APK and AAB

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    env:
      APP_DIR: react-native-gsm-sip-gateway/telon-gateway-app
      ANDROID_DIR: ${{ env.APP_DIR }}/android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: react-native-gsm-sip-gateway

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ env.APP_DIR }}/package-lock.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install React-Native CLI globally
        run: npm install -g @react-native-community/cli

      - name: Install app dependencies
        working-directory: ${{ env.APP_DIR }}
        run: npm ci --legacy-peer-deps

      - name: Verify CLI-Android module
        working-directory: ${{ env.APP_DIR }}
        run: |
          test -d node_modules/@react-native-community/cli-platform-android \
            && echo "CLI-Android module present" \
            || npm install @react-native-community/cli-platform-android --save-dev

      - name: Create local.properties
        working-directory: ${{ env.ANDROID_DIR }}
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Make Gradlew executable
        working-directory: ${{ env.ANDROID_DIR }}
        run: chmod +x gradlew

      - name: Clean Android build
        working-directory: ${{ env.ANDROID_DIR }}
        run: ./gradlew clean

      - name: Build Android APK
        working-directory: ${{ env.ANDROID_DIR }}
        run: ./gradlew assembleRelease --stacktrace --info
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ${{ env.ANDROID_DIR }}/app/build/outputs/apk/release/app-release.apk

      - name: Build Android AAB
        working-directory: ${{ env.ANDROID_DIR }}
        run: ./gradlew bundleRelease --stacktrace --info
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: ${{ env.ANDROID_DIR }}/app/build/outputs/bundle/release/app-release.aab
