# A completely revised and robust workflow for building the Android app.
# This version uses a single job to ensure the environment is consistent.

name: Build Android APK and AAB

on:
  push:
    branches:
      - "**" # Runs on any push to any branch

jobs:
  build_android:
    name: Build Android Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Checks out your main repo into this specific folder
          path: react-native-gsm-sip-gateway

      - name: Checkout required dependencies
        # This step correctly runs inside the main repo folder
        working-directory: react-native-gsm-sip-gateway
        run: |
          git clone https://github.com/telon-org/react-native-tele.git
          git clone https://github.com/telon-org/react-native-sip2.git
          git clone https://github.com/telon-org/react-native-replace-dialer.git

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        # THIS IS THE CRITICAL FIX: Using --legacy-peer-deps to solve the
        # dependency conflict which was causing npm install to fail.
        run: npm install --legacy-peer-deps
        working-directory: react-native-gsm-sip-gateway/telon-gateway-app

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        working-directory: react-native-gsm-sip-gateway/telon-gateway-app

      - name: Make Gradlew executable
        run: chmod +x gradlew
        working-directory: react-native-gsm-sip-gateway/telon-gateway-app/android

      - name: Build Android APK
        run: ./gradlew assembleRelease
        working-directory: react-native-gsm-sip-gateway/telon-gateway-app/android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: react-native-gsm-sip-gateway/telon-gateway-app/android/app/build/outputs/apk/release/app-release.apk

      - name: Build Android App Bundle (AAB)
        run: ./gradlew bundleRelease
        working-directory: react-native-gsm-sip-gateway/telon-gateway-app/android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: react-native-gsm-sip-gateway/telon-gateway-app/android/app/build/outputs/bundle/release/app-release.aab
