# Modernized GitHub Actions workflow
name: Build Android APK and AAB

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build Android Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: react-native-gsm-sip-gateway

      - name: Set working directory
        run: echo "WORK_DIR=react-native-gsm-sip-gateway/telon-gateway-app" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: |
          git clone https://github.com/telon-org/react-native-replace-dialer.git
          npm install

      - name: Patch Library Source Code
        working-directory: ${{ env.WORK_DIR }}
        run: |
          # Patch react-native-sip2
          sed -i '/android {/a \    namespace "com.reactlibrary.sip2"\
              buildFeatures {\
                  buildConfig false\
              }' node_modules/react-native-sip2/android/build.gradle
          
          # Patch react-native-tele
          sed -i '/android {/a \    namespace "com.reactlibrary.tele"\
              buildFeatures {\
                  buildConfig false\
              }' node_modules/react-native-tele/android/build.gradle
          
          # Patch react-native-replace-dialer
          sed -i '/android {/a \    namespace "com.reactlibrary.replacedialer"\
              buildFeatures {\
                  buildConfig false\
              }' react-native-replace-dialer/android/build.gradle

      - name: Create local.properties
        working-directory: ${{ env.WORK_DIR }}/android
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Make Gradlew executable
        working-directory: ${{ env.WORK_DIR }}/android
        run: chmod +x gradlew

      - name: Clean build
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew clean

      - name: Build Android APK
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Android App Bundle (AAB)
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew bundleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.WORK_DIR }}/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: ${{ env.WORK_DIR }}/android/app/build/outputs/bundle/release/app-release.aab
