# Fixed GitHub Actions workflow with corrected Gradle paths
name: Build Android APK and AAB

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build_android:
    name: Build Android Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: react-native-gsm-sip-gateway

      - name: Set working directory
        run: |
          if [ -d "react-native-gsm-sip-gateway/telon-gateway-app" ]; then
            echo "WORK_DIR=react-native-gsm-sip-gateway/telon-gateway-app" >> $GITHUB_ENV
          elif [ -f "react-native-gsm-sip-gateway/package.json" ]; then
            echo "WORK_DIR=react-native-gsm-sip-gateway" >> $GITHUB_ENV
          else
            echo "ERROR: No package.json found in expected locations"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: ${{ env.WORK_DIR }}/package-lock.json

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '6249121'

      - name: Install Dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: |
          npm install

      - name: Create local.properties
        working-directory: ${{ env.WORK_DIR }}/android
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Make Gradlew executable
        working-directory: ${{ env.WORK_DIR }}/android
        run: chmod +x gradlew

      - name: Clean build
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew clean

      - name: Build Android APK
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew assembleRelease --stacktrace --info
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Android App Bundle (AAB)
        working-directory: ${{ env.WORK_DIR }}/android
        run: ./gradlew bundleRelease --stacktrace --info
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ${{ env.WORK_DIR }}/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: ${{ env.WORK_DIR }}/android/app/build/outputs/bundle/release/app-release.aab
