name: Build Android Gateway APK

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    # NEW: This default setting tells all 'run' steps to execute inside this directory
    defaults:
      run:
        working-directory: ./sip-gateway

    steps:
      # Step 1: Checks out the repository, creating the 'sip-gateway' directory
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # This ensures the checkout places the repo content in a 'sip-gateway' subfolder
          path: sip-gateway

      # Step 2: List files to confirm the structure
      - name: List files in workspace
        run: ls -la
        working-directory: . # Run this step at the root to see the sub-directory

      # Step 3: Set up JDK version 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Set up Node.js version 18
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          # Tell the cache where to find the lock file
          cache-dependency-path: sip-gateway/yarn.lock

      # Step 5: Install Yarn Dependencies (will run inside 'sip-gateway')
      - name: Install Yarn Dependencies
        run: yarn install

      # Step 6: Build the release APK (will run inside 'sip-gateway')
      - name: Build Android Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # Step 7: Upload the generated APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gsm-sip-gateway-apk
          # The path is relative to the workspace root
          path: sip-gateway/android/app/build/outputs/apk/release/app-release.apk
